# Generated by Django 4.2.10 on 2025-05-17 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_ar', models.CharField(max_length=100, verbose_name='name in Arabic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_ar', models.CharField(max_length=200, verbose_name='title in Arabic')),
                ('description', models.TextField(verbose_name='description')),
                ('description_ar', models.TextField(verbose_name='description in Arabic')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='main image')),
                ('client', models.CharField(max_length=100, verbose_name='client')),
                ('date', models.DateField(verbose_name='date')),
                ('featured', models.BooleanField(default=False, verbose_name='featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='image')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'project image',
                'verbose_name_plural': 'project images',
                'ordering': ['order'],
            },
        ),
    ]
