# Generated by Django 4.2.10 on 2025-09-28 02:48

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to=projects.models.project_image_path, verbose_name='main image'),
        ),
    ]
