# Generated by Django 4.2.10 on 2025-09-29 23:25

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=projects.models.project_gallery_image_path, verbose_name='image'),
        ),
    ]
