# Generated by Django 4.2.10 on 2025-11-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city_country', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('graphic_designer', 'Graphic Designer'), ('motion_designer', 'Motion Designer'), ('content_creator', 'Content Creator'), ('media_buyer', 'Media Buyer')], max_length=50)),
                ('work_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('remote', 'Remote'), ('internship', 'Internship')], max_length=20)),
                ('years_of_experience', models.CharField(choices=[('0_1', '<1'), ('1_3', '1–3'), ('3_5', '3–5'), ('5_plus', '5+')], max_length=10)),
                ('about_you', models.TextField()),
                ('tools', models.JSONField(default=list)),
                ('portfolio_link', models.URLField()),
                ('worked_in_agency_before', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
